name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-ci:
    name: test-ci
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      # This is required to work around https://github.com/npm/cli/issues/2610 
      # for the case of dependabot PRs. 
      - run: git config url."https://".insteadOf ssh://
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: install deps
        run: pnpm install
      - name: build sdk
        run: pnpm build
      - name: lint
        run: pnpm lint
      - name: check ts
        run: pnpm lint:ts
      - name: test
        run: pnpm test:all
