name: NPM Package Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/626179414504/locations/global/workloadIdentityPools/ga-embedded-app-sdk/providers/ga-embedded-app-sdk'
          service_account: 'ga-embedded-app-sdk@discord-app-city-prd.iam.gserviceaccount.com'
      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
          secrets: |-
            NPM_TOKEN:discord-app-city-prd/embedded-app-sdk-deploy-token
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ steps.secrets.outputs.NPM_TOKEN }}
