name: sdk playground production deploy
on:
  push:
    branches: [main]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      # build latest embedded-app-sdk
      - name: build latest embedded-app-sdk
        run: |
          pnpm install && pnpm build

      # create env file
      - name: create env file
        run: |
          cd examples/sdk-playground
          echo "${{ secrets.ENV_FILE }}" > .env.production

      # build sdk playground client
      - name: build sdk-playground client
        run: |
          cd examples/sdk-playground/packages/client
          pnpm build

      # deploy client
      - name: deploy client
        uses: cloudflare/wrangler-action@v3.6.1
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: examples/sdk-playground/packages/client
          command: pages publish --project-name=sdk-playground dist
          wranglerVersion: '3.52.0'

      # deploy server
      - name: deploy server
        uses: cloudflare/wrangler-action@v3.6.1
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          preCommands: ./handle-wrangler-secrets.sh production remote
          workingDirectory: examples/sdk-playground/packages/server
          command: publish src/index.ts --env production
          wranglerVersion: '3.52.0'
